name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release.yml@368e641e28009262f686b74f444a2a0b8600fabd # Build-Tools main (checkout v7)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: SimpleSFTPServer
      dist_subfolder: "Simple SFTP Server"
      python_version: "3.14"
      build_command: "Build_Simple_SFTP_Server.bat"
      app_id: "1d184cf8-3eba-4348-869d-f299485d38f6"
